### ISSUE TITLE
Your approach

### ISSUE THREAD

**Issue by etavener** [filipwiniarski/scully-plugins#3]
I've been looking at doing something similar. I have some reservations about your implementation though.

1. You optimise the css for the static file, does this remove Angular then?

My thoughts to get this working with Angular is to:
1. Take just the css required to render the static page and inline it in the head.( as you have done)
2. Move the existing `<link>` to the application css and move down in priority.

I currently use an Angular delay plugin and I think maybe something similar can be used for the application css.

I would be interested to get your thoughts on this.

**Comment by filipwiniarski** [comment]
@etavener Scully outputs global styles as inline CSS so I wrote this plugin to filter those lines and output only those styles which are needed for a static page to render (the goal was to minimize html size). This plugin has no support for linked styles yet, so it won't effect those in any way. Please let me know if that was your concern, thanks!
